services:
#  bot:
#    build: .
#    env_file:
#      - .env
#    volumes:
#      - ./settings.json:/settings.json
#      - ./pics:/pics
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_furry_bot
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
volumes:
  db: